import os

FACESHAPE_TOKEN=os.getenv('FACESHAPE_TOKEN')
HUGGINGFACE_API_TOKEN=os.getenv('HUGGINGFACE_API_TOKEN')

FACEPLUSPLUS_API_KEY=os.getenv('FACEPLUSPLUS_API_KEY')
FACEPLUSPLUS_API_SECRET=os.getenv('FACEPLUSPLUS_API_SECRET')

PIXLR_CLIENT_KEY=os.getenv('PIXLR_CLIENT_KEY')
PIXLR_CLIENT_SECRET=os.getenv('PIXLR_CLIENT_SECRET')