import os

FACESHAPE_TOKEN=os.getenv('FACESHAPE_TOKEN')
HUGGINGFACE_API_TOKEN=os.getenv('HUGGINGFACE_API_TOKEN')

FACEPLUSPLUS_API_KEY=os.getenv('FACEPLUSPLUS_API_KEY')
FACEPLUSPLUS_API_SECRET=os.getenv('FACEPLUSPLUS_API_SECRET')

PIXLR_CLIENT_KEY=os.getenv('PIXLR_CLIENT_KEY')
PIXLR_CLIENT_SECRET=os.getenv('PIXLR_CLIENT_SECRET')

LEONARDO_AI_TOKEN=os.getenv('LEONARDO_AI_TOKEN')

DISCORD_BOT_TOKEN=os.getenv('DISCORD_BOT_TOKEN')
DISCORD_SERVER_ID=os.getenv('DISCORD_SERVER_ID')
DISCORD_CHANNEL_ID=os.getenv('DISCORD_CHANNEL_ID')

USEAPI_TOKEN=os.getenv('USEAPI_TOKEN')
USEAPI_DISCORD=os.getenv('USEAPI_DISCORD')
USEAPI_SERVER=os.getenv('USEAPI_SERVER')
USEAPI_CHANNEL=os.getenv('USEAPI_CHANNEL')
USEAPI_CALLBACK=os.getenv('USEAPI_CALLBACK')